import { MigrationInterface, QueryRunner } from "typeorm";

export class AddNote1687618459371 implements MigrationInterface {
    name = 'AddNote1687618459371'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "REGIONS" ADD "NOTE" varchar2(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "REGIONS" DROP COLUMN "REGION_ID"`);
        await queryRunner.query(`ALTER TABLE "REGIONS" ADD "REGION_ID" number NOT NULL`);
        await queryRunner.query(`ALTER TABLE "REGIONS" ADD CONSTRAINT "PK_e6360a7aed3df58712e3ba90597" PRIMARY KEY ("REGION_ID")`);
        await queryRunner.query(`ALTER TABLE "REGIONS" DROP COLUMN "REGION_NAME"`);
        await queryRunner.query(`ALTER TABLE "REGIONS" ADD "REGION_NAME" varchar2(255) NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "REGIONS" DROP COLUMN "REGION_NAME"`);
        await queryRunner.query(`ALTER TABLE "REGIONS" ADD "REGION_NAME" varchar2(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "REGIONS" DROP CONSTRAINT "PK_e6360a7aed3df58712e3ba90597"`);
        await queryRunner.query(`ALTER TABLE "REGIONS" DROP COLUMN "REGION_ID"`);
        await queryRunner.query(`ALTER TABLE "REGIONS" ADD "REGION_ID" number GENERATED BY DEFAULT AS IDENTITY`);
        await queryRunner.query(`ALTER TABLE "REGIONS" DROP COLUMN "NOTE"`);
    }

}
